name: Linux

on: [push]

jobs:
  x64:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install QT
      run: sudo apt-get install qt5-default
    - name: Qmake HWA
      run: qmake Hardware-Monitor-Applet.pro
    - name: Make
      run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: X64_linux
        path: ${{ github.workspace }}/
      
